name: staff_time
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.17.0
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
