name: staff_time
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^6.2.1
  intl: ^0.20.2

  # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.17.0

  # Caching / Storage
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.5.3
  hive: ^2.2.3

  # UI Helpers
  shimmer: ^3.0.0
  table_calendar: ^3.2.0

  # Launcher Icons
  flutter_launcher_icons: ^0.14.3
  
  # Flutter Native Splash
  flutter_native_splash: ^2.4.2
  flag: ^7.0.0
  country_flags: ^3.2.0
  cloud_functions: ^4.7.6
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation for Hive
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Staff_Time_Icon.png
    - Assets/Staff_Time_Icon_green.png

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/Staff_Time_Icon.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#FFFFFF"
  image: Assets/Staff_Time_Icon_green.png
  android_gravity: fill
  ios_content_mode: scaleAspectFit
  android_12:
    image: Assets/Staff_Time_Icon_green.png
    icon_background_color: "#FFFFFF"