// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvjnGpZx0YcwtGx2voq1c9rgQR2ddw5wc',
    appId: '1:299375358520:web:939ec6e392c4506aa4eccd',
    messagingSenderId: '299375358520',
    projectId: 'staff-nfc-attendance',
    authDomain: 'staff-nfc-attendance.firebaseapp.com',
    storageBucket: 'staff-nfc-attendance.firebasestorage.app',
    measurementId: 'G-ZBY2TCC5WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt58eq-uMlweRFUYbhredoICraj-V5Ucs',
    appId: '1:299375358520:android:6191f93b4eab8596a4eccd',
    messagingSenderId: '299375358520',
    projectId: 'staff-nfc-attendance',
    storageBucket: 'staff-nfc-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlFyyGeq9ZaI5yzNPIPNkdr3ye8Q2yVlU',
    appId: '1:299375358520:ios:0e152aed28f48521a4eccd',
    messagingSenderId: '299375358520',
    projectId: 'staff-nfc-attendance',
    storageBucket: 'staff-nfc-attendance.firebasestorage.app',
    iosBundleId: 'com.example.staffTime',
  );
}
