import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'Screens/Dashboard.dart';
import 'Screens/otp_verification_screen.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure`
import 'package:staff_time/Theme/app_theme.dart';
import 'Screens/phone_login_screen.dart';

void main() async {
  // This needs to happen first - keep the binding for later
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  
  // Tell Flutter to preserve the splash screen
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  
  // Simulate loading with a deliberate delay - just for testing
  // You can remove this in production if your initialization takes long enough
  await Future.delayed(const Duration(seconds: 3));
  
  try {
    // Initialize Firebase - your actual app startup logic
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    print("Error initializing app: $e");
  } finally {
    // Always remove splash screen when initialization is complete
    FlutterNativeSplash.remove();
  }
  
  // Start your app after initialization
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: AppTheme.lightTheme,
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: Dashboard(),
      ),
    );
  }
}